import type { Metadata } from "next"; 
import "./globals.css";

import { AuthProvider } from '@/context/AuthContext';

import ChatlingWidget from "@/components/ui/chatlingWidget"


import Script from "next/script";

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body 
      >
        <Script id="chatling-config">
          {`
            window.chtlConfig = { chatbotId: "9197784116" };
          `}
        </Script>
        <Script
          id="chatling-embed-script"
          strategy="afterInteractive"
          src="https://chatling.ai/js/embed.js"
          data-id="9197784116"
        />
        <AuthProvider>
          {children}

        </AuthProvider>
      </body>
    </html>
  );
}
